version: '3'
services:
  timesheet:
    build: .
    container_name: timesheet
    environment:
      # Generate secret Key: https://django-secret-key-generator.netlify.app/
      - SECRET_KEY=YOUR_SECRET_KEY_HERE
      - HOSTNAME=YOUR-HOSTNAME-HERE
    image: timesheet:latest
    ports:
      - 8000:8000
    restart: unless-stopped
  timesheetdb:
    container_name: timesheetdb
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - 5432:5432
    image: postgres:13
    restart: unless-stopped
