# Generated by Django 4.1.1 on 2022-12-20 00:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0002_shift_finish"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="shift",
            name="income",
        ),
    ]
