# Generated by Django 4.1.1 on 2023-01-04 01:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0003_remove_shift_income"),
    ]

    operations = [
        migrations.AlterField(
            model_name="period",
            name="job",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="periods",
                to="jobs.job",
            ),
        ),
        migrations.AlterField(
            model_name="shift",
            name="period",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="shifts",
                to="jobs.period",
            ),
        ),
    ]
